### ISSUE TITLE
关于论文实验的问题

### ISSUE THREAD

**Issue by zhangshuoneu** [UESTC-nnLab/LGU-SLAM#1]
你好同学，恭喜完成了论文撰写。这边有几个问题想问下。
1. 论文中提到只使用了一张3090显卡，训练了250k步，这个训练时间应该不短，应该是在一周以上，想问下消融实验也是使用完整的TartanAir数据集训练的吗，这样的话实验时间是比较长的。
2. 单卡和多卡训练的性能你有做过比较吗。DROID-SLAM是使用4张卡训练的
3. 有没有自采一些数据进行实验，验证深度学习SLAM的泛化性。
4. 论文中提到的residual loss描述似乎不正确，这个损失是网络直接预测的光流，和位姿、深度重投影得到的光流的差值。

**Comment by huangliqwe2020** [comment]
同学你好！感谢同学的提问，我将逐一作出回答：
（1）我们实验只用到一张3090显卡进行训练，完成训练250k需要4天的时间，我们训练阶段batchsize为2，输入帧长为4。消融实验的模型也是在去掉验证集后的tartanair数据集上训练的。
（2）没有进行过单卡和多卡的性能对比。
（3）没有自采数据进行实验，但是目前我们正在其他公开数据集比如Replica上与3DGS结合进行相关实验。目前在Replica的office0上取得不错的位姿估计和建图效果，这一步我们也是参照了Go-slam和SplaTAM两个工作。具体的实验展示和与3DGS结合的代码我们下周会更新到github中。后续我们会采集现实场景中的数据集进行进一步的验证，也感谢同学的建议。
（4）之前回答有问题，sorry，但是论文中的表述是与代码一致的，只考虑一次BA优化的话，BA之前最终的Pkij是target=coord1+delta, BA之后的Pkij是通过优化后的位姿和深度进行重投影得到的。
