### ISSUE TITLE
model weights download

### ISSUE THREAD

**Issue by jedivova** [UESTC-nnLab/LGU-SLAM#4]
Hi!

Got error while trying to run demo:
`python demo.py --imagedir=data/abandonedfactory --calib=calib/tartan.txt --stride=2`
error:
```
  File "/root/miniconda3/envs/droidenv/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'demo.pth'
```

There is no information in the readme how/where to download the model weights file. Can you provide an URL please?

Thank you!

**Comment by huangliqwe2020** [comment]
Thanks for your attention! Could you provide me with your email? Please update the lowMem_defSample.cu in offersample_LGU.

**Comment by jedivova** [comment]
a

> Thanks for your attention! Could you provide me with your email? Please update the lowMem_defSample.cu in offersample_LGU.

jedi.vova@gmail.com
